import tensorflow as tf
hello = tf.constant("hello tensorflow")
sess = tf.Session()
print(sess.run(hello))
print("hello zyw")
print('hello sxh')
#print('hello zyw sxh')
print('hello my wife')
print('2 sixth')
print('7th')